//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 03:29:45 PM ICT 
//


package id.ac.univpgri_palembang.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classReversalRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="classReversalRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kodeBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passwordBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kodeChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kodeTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nomorPembayaran" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tanggalTransaksi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalnominal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tanggalTransaksiAsal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTransaksi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classReversalRequest", propOrder = {
    "kodeBank",
    "passwordBank",
    "kodeChannel",
    "kodeTerminal",
    "nomorPembayaran",
    "tanggalTransaksi",
    "totalnominal",
    "tanggalTransaksiAsal",
    "idTransaksi"
})
public class ClassReversalRequest {

    protected String kodeBank;
    protected String passwordBank;
    protected String kodeChannel;
    protected String kodeTerminal;
    protected String nomorPembayaran;
    protected String tanggalTransaksi;
    protected String totalnominal;
    protected String tanggalTransaksiAsal;
    protected String idTransaksi;

    /**
     * Gets the value of the kodeBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeBank() {
        return kodeBank;
    }

    /**
     * Sets the value of the kodeBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeBank(String value) {
        this.kodeBank = value;
    }

    /**
     * Gets the value of the passwordBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordBank() {
        return passwordBank;
    }

    /**
     * Sets the value of the passwordBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordBank(String value) {
        this.passwordBank = value;
    }

    /**
     * Gets the value of the kodeChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeChannel() {
        return kodeChannel;
    }

    /**
     * Sets the value of the kodeChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeChannel(String value) {
        this.kodeChannel = value;
    }

    /**
     * Gets the value of the kodeTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeTerminal() {
        return kodeTerminal;
    }

    /**
     * Sets the value of the kodeTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeTerminal(String value) {
        this.kodeTerminal = value;
    }

    /**
     * Gets the value of the nomorPembayaran property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomorPembayaran() {
        return nomorPembayaran;
    }

    /**
     * Sets the value of the nomorPembayaran property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomorPembayaran(String value) {
        this.nomorPembayaran = value;
    }

    /**
     * Gets the value of the tanggalTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTanggalTransaksi() {
        return tanggalTransaksi;
    }

    /**
     * Sets the value of the tanggalTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTanggalTransaksi(String value) {
        this.tanggalTransaksi = value;
    }

    /**
     * Gets the value of the totalnominal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalnominal() {
        return totalnominal;
    }

    /**
     * Sets the value of the totalnominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalnominal(String value) {
        this.totalnominal = value;
    }

    /**
     * Gets the value of the tanggalTransaksiAsal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTanggalTransaksiAsal() {
        return tanggalTransaksiAsal;
    }

    /**
     * Sets the value of the tanggalTransaksiAsal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTanggalTransaksiAsal(String value) {
        this.tanggalTransaksiAsal = value;
    }

    /**
     * Gets the value of the idTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTransaksi() {
        return idTransaksi;
    }

    /**
     * Sets the value of the idTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTransaksi(String value) {
        this.idTransaksi = value;
    }

}
