//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 03:29:45 PM ICT 
//


package id.ac.univpgri_palembang.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Datamhs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Datamhs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomorInduk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fakultas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jurusan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="periode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="angkatan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datamhs", propOrder = {
    "nomorInduk",
    "nama",
    "fakultas",
    "jurusan",
    "strata",
    "periode",
    "angkatan"
})
public class Datamhs {

    protected String nomorInduk;
    protected String nama;
    protected String fakultas;
    protected String jurusan;
    protected String strata;
    protected String periode;
    protected String angkatan;

    /**
     * Gets the value of the nomorInduk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomorInduk() {
        return nomorInduk;
    }

    /**
     * Sets the value of the nomorInduk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomorInduk(String value) {
        this.nomorInduk = value;
    }

    /**
     * Gets the value of the nama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNama() {
        return nama;
    }

    /**
     * Sets the value of the nama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNama(String value) {
        this.nama = value;
    }

    /**
     * Gets the value of the fakultas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFakultas() {
        return fakultas;
    }

    /**
     * Sets the value of the fakultas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFakultas(String value) {
        this.fakultas = value;
    }

    /**
     * Gets the value of the jurusan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurusan() {
        return jurusan;
    }

    /**
     * Sets the value of the jurusan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurusan(String value) {
        this.jurusan = value;
    }

    /**
     * Gets the value of the strata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrata() {
        return strata;
    }

    /**
     * Sets the value of the strata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrata(String value) {
        this.strata = value;
    }

    /**
     * Gets the value of the periode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriode(String value) {
        this.periode = value;
    }

    /**
     * Gets the value of the angkatan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAngkatan() {
        return angkatan;
    }

    /**
     * Sets the value of the angkatan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAngkatan(String value) {
        this.angkatan = value;
    }

}
