//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 03:29:45 PM ICT 
//


package id.ac.univpgri_palembang.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemPembayaran complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemPembayaran">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kodeTransaksi" type="{http://ws.univpgri-palembang.ac.id/}ArrayOfString" minOccurs="0"/>
 *         &lt;element name="deskripsi" type="{http://ws.univpgri-palembang.ac.id/}ArrayOfString" minOccurs="0"/>
 *         &lt;element name="nominalTransaksi" type="{http://ws.univpgri-palembang.ac.id/}ArrayOfString" minOccurs="0"/>
 *         &lt;element name="kodeRekening" type="{http://ws.univpgri-palembang.ac.id/}ArrayOfString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemPembayaran", propOrder = {
    "kodeTransaksi",
    "deskripsi",
    "nominalTransaksi",
    "kodeRekening"
})
public class ItemPembayaran {

    protected ArrayOfString kodeTransaksi;
    protected ArrayOfString deskripsi;
    protected ArrayOfString nominalTransaksi;
    protected ArrayOfString kodeRekening;

    /**
     * Gets the value of the kodeTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getKodeTransaksi() {
        return kodeTransaksi;
    }

    /**
     * Sets the value of the kodeTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setKodeTransaksi(ArrayOfString value) {
        this.kodeTransaksi = value;
    }

    /**
     * Gets the value of the deskripsi property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getDeskripsi() {
        return deskripsi;
    }

    /**
     * Sets the value of the deskripsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setDeskripsi(ArrayOfString value) {
        this.deskripsi = value;
    }

    /**
     * Gets the value of the nominalTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getNominalTransaksi() {
        return nominalTransaksi;
    }

    /**
     * Sets the value of the nominalTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setNominalTransaksi(ArrayOfString value) {
        this.nominalTransaksi = value;
    }

    /**
     * Gets the value of the kodeRekening property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getKodeRekening() {
        return kodeRekening;
    }

    /**
     * Sets the value of the kodeRekening property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setKodeRekening(ArrayOfString value) {
        this.kodeRekening = value;
    }

}
