//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 03:29:45 PM ICT 
//


package id.ac.univpgri_palembang.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.ac.univpgri_palembang.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.ac.univpgri_palembang.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datamhs }
     * 
     */
    public Datamhs createDatamhs() {
        return new Datamhs();
    }

    /**
     * Create an instance of {@link ClassInquiryRequest }
     * 
     */
    public ClassInquiryRequest createClassInquiryRequest() {
        return new ClassInquiryRequest();
    }

    /**
     * Create an instance of {@link ClassPaymentRequest }
     * 
     */
    public ClassPaymentRequest createClassPaymentRequest() {
        return new ClassPaymentRequest();
    }

    /**
     * Create an instance of {@link InquiryRespon }
     * 
     */
    public InquiryRespon createInquiryRespon() {
        return new InquiryRespon();
    }

    /**
     * Create an instance of {@link ClassReversalRequest }
     * 
     */
    public ClassReversalRequest createClassReversalRequest() {
        return new ClassReversalRequest();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ReversalResponse }
     * 
     */
    public ReversalResponse createReversalResponse() {
        return new ReversalResponse();
    }

    /**
     * Create an instance of {@link InquiryResponse }
     * 
     */
    public InquiryResponse createInquiryResponse() {
        return new InquiryResponse();
    }

    /**
     * Create an instance of {@link ReversalRespon }
     * 
     */
    public ReversalRespon createReversalRespon() {
        return new ReversalRespon();
    }

    /**
     * Create an instance of {@link PaymentResponse }
     * 
     */
    public PaymentResponse createPaymentResponse() {
        return new PaymentResponse();
    }

    /**
     * Create an instance of {@link ItemPembayaran }
     * 
     */
    public ItemPembayaran createItemPembayaran() {
        return new ItemPembayaran();
    }

    /**
     * Create an instance of {@link PaymentRespon }
     * 
     */
    public PaymentRespon createPaymentRespon() {
        return new PaymentRespon();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Applicationfault }
     * 
     */
    public Applicationfault createApplicationfault() {
        return new Applicationfault();
    }

    /**
     * Create an instance of {@link Inquiry }
     * 
     */
    public Inquiry createInquiry() {
        return new Inquiry();
    }

    /**
     * Create an instance of {@link Reversal }
     * 
     */
    public Reversal createReversal() {
        return new Reversal();
    }

}
