//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 03:29:45 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.univpgri-palembang.ac.id/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package id.ac.univpgri_palembang.ws;
