//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 06:31:15 PM ICT 
//


package h2humplg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="H2H-InquryResult" type="{H2hUmplg}InquiryResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "h2HInquryResult"
})
@XmlRootElement(name = "H2H-InquryResponse")
public class H2HInquryResponse {

    @XmlElement(name = "H2H-InquryResult")
    protected InquiryResponse h2HInquryResult;

    /**
     * Gets the value of the h2HInquryResult property.
     * 
     * @return
     *     possible object is
     *     {@link InquiryResponse }
     *     
     */
    public InquiryResponse getH2HInquryResult() {
        return h2HInquryResult;
    }

    /**
     * Sets the value of the h2HInquryResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquiryResponse }
     *     
     */
    public void setH2HInquryResult(InquiryResponse value) {
        this.h2HInquryResult = value;
    }

}
