//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 06:31:15 PM ICT 
//


package h2humplg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idTagihan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kodeBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passwordBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kodeChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kodeTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nomorPembayaran" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="waktuTransaksiBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalNominal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kodeUnikBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nomorJurnalBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idTagihan",
    "kodeBank",
    "passwordBank",
    "kodeChannel",
    "kodeTerminal",
    "nomorPembayaran",
    "waktuTransaksiBank",
    "totalNominal",
    "kodeUnikBank",
    "nomorJurnalBank"
})
@XmlRootElement(name = "H2H-Payment")
public class H2HPayment {

    protected String idTagihan;
    protected String kodeBank;
    protected String passwordBank;
    protected String kodeChannel;
    protected String kodeTerminal;
    protected String nomorPembayaran;
    protected String waktuTransaksiBank;
    protected String totalNominal;
    protected String kodeUnikBank;
    protected String nomorJurnalBank;

    /**
     * Gets the value of the idTagihan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTagihan() {
        return idTagihan;
    }

    /**
     * Sets the value of the idTagihan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTagihan(String value) {
        this.idTagihan = value;
    }

    /**
     * Gets the value of the kodeBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeBank() {
        return kodeBank;
    }

    /**
     * Sets the value of the kodeBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeBank(String value) {
        this.kodeBank = value;
    }

    /**
     * Gets the value of the passwordBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordBank() {
        return passwordBank;
    }

    /**
     * Sets the value of the passwordBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordBank(String value) {
        this.passwordBank = value;
    }

    /**
     * Gets the value of the kodeChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeChannel() {
        return kodeChannel;
    }

    /**
     * Sets the value of the kodeChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeChannel(String value) {
        this.kodeChannel = value;
    }

    /**
     * Gets the value of the kodeTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeTerminal() {
        return kodeTerminal;
    }

    /**
     * Sets the value of the kodeTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeTerminal(String value) {
        this.kodeTerminal = value;
    }

    /**
     * Gets the value of the nomorPembayaran property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomorPembayaran() {
        return nomorPembayaran;
    }

    /**
     * Sets the value of the nomorPembayaran property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomorPembayaran(String value) {
        this.nomorPembayaran = value;
    }

    /**
     * Gets the value of the waktuTransaksiBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaktuTransaksiBank() {
        return waktuTransaksiBank;
    }

    /**
     * Sets the value of the waktuTransaksiBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaktuTransaksiBank(String value) {
        this.waktuTransaksiBank = value;
    }

    /**
     * Gets the value of the totalNominal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalNominal() {
        return totalNominal;
    }

    /**
     * Sets the value of the totalNominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalNominal(String value) {
        this.totalNominal = value;
    }

    /**
     * Gets the value of the kodeUnikBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeUnikBank() {
        return kodeUnikBank;
    }

    /**
     * Sets the value of the kodeUnikBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeUnikBank(String value) {
        this.kodeUnikBank = value;
    }

    /**
     * Gets the value of the nomorJurnalBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomorJurnalBank() {
        return nomorJurnalBank;
    }

    /**
     * Sets the value of the nomorJurnalBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomorJurnalBank(String value) {
        this.nomorJurnalBank = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "H2HPayment [idTagihan=" + idTagihan + ", kodeBank=" + kodeBank
				+ ", passwordBank=" + passwordBank + ", kodeChannel="
				+ kodeChannel + ", kodeTerminal=" + kodeTerminal
				+ ", nomorPembayaran=" + nomorPembayaran
				+ ", waktuTransaksiBank=" + waktuTransaksiBank
				+ ", totalNominal=" + totalNominal + ", kodeUnikBank="
				+ kodeUnikBank + ", nomorJurnalBank=" + nomorJurnalBank + "]";
	}

}
