//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 06:31:15 PM ICT 
//


package h2humplg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="H2H-ReversalResult" type="{H2hUmplg}ReversalResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "h2HReversalResult"
})
@XmlRootElement(name = "H2H-ReversalResponse")
public class H2HReversalResponse {

    @XmlElement(name = "H2H-ReversalResult")
    protected ReversalResponse h2HReversalResult;

    /**
     * Gets the value of the h2HReversalResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReversalResponse }
     *     
     */
    public ReversalResponse getH2HReversalResult() {
        return h2HReversalResult;
    }

    /**
     * Sets the value of the h2HReversalResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReversalResponse }
     *     
     */
    public void setH2HReversalResult(ReversalResponse value) {
        this.h2HReversalResult = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "H2HReversalResponse [h2HReversalResult=" + h2HReversalResult
				+ "]";
	}

}
