//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 06:31:15 PM ICT 
//


package h2humplg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the h2humplg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: h2humplg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link H2HPaymentResponse }
     * 
     */
    public H2HPaymentResponse createH2HPaymentResponse() {
        return new H2HPaymentResponse();
    }

    /**
     * Create an instance of {@link PaymentResponse }
     * 
     */
    public PaymentResponse createPaymentResponse() {
        return new PaymentResponse();
    }

    /**
     * Create an instance of {@link H2HPayment }
     * 
     */
    public H2HPayment createH2HPayment() {
        return new H2HPayment();
    }

    /**
     * Create an instance of {@link H2HInquryResponse }
     * 
     */
    public H2HInquryResponse createH2HInquryResponse() {
        return new H2HInquryResponse();
    }

    /**
     * Create an instance of {@link InquiryResponse }
     * 
     */
    public InquiryResponse createInquiryResponse() {
        return new InquiryResponse();
    }

    /**
     * Create an instance of {@link H2HReversalResponse }
     * 
     */
    public H2HReversalResponse createH2HReversalResponse() {
        return new H2HReversalResponse();
    }

    /**
     * Create an instance of {@link ReversalResponse }
     * 
     */
    public ReversalResponse createReversalResponse() {
        return new ReversalResponse();
    }

    /**
     * Create an instance of {@link H2HReversal }
     * 
     */
    public H2HReversal createH2HReversal() {
        return new H2HReversal();
    }

    /**
     * Create an instance of {@link H2HInqury }
     * 
     */
    public H2HInqury createH2HInqury() {
        return new H2HInqury();
    }

    /**
     * Create an instance of {@link ArrayOfPaymentItem }
     * 
     */
    public ArrayOfPaymentItem createArrayOfPaymentItem() {
        return new ArrayOfPaymentItem();
    }

    /**
     * Create an instance of {@link PaymentItem }
     * 
     */
    public PaymentItem createPaymentItem() {
        return new PaymentItem();
    }

}
