//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 06:31:15 PM ICT 
//


package h2humplg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kodeTransaksi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deskripsiPendek" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deskripsiPanjang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nominalTransaksi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentItem", propOrder = {
    "kodeTransaksi",
    "deskripsiPendek",
    "deskripsiPanjang",
    "nominalTransaksi"
})
public class PaymentItem {

    protected String kodeTransaksi;
    protected String deskripsiPendek;
    protected String deskripsiPanjang;
    protected String nominalTransaksi;

    /**
     * Gets the value of the kodeTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeTransaksi() {
        return kodeTransaksi;
    }

    /**
     * Sets the value of the kodeTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeTransaksi(String value) {
        this.kodeTransaksi = value;
    }

    /**
     * Gets the value of the deskripsiPendek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeskripsiPendek() {
        return deskripsiPendek;
    }

    /**
     * Sets the value of the deskripsiPendek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeskripsiPendek(String value) {
        this.deskripsiPendek = value;
    }

    /**
     * Gets the value of the deskripsiPanjang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeskripsiPanjang() {
        return deskripsiPanjang;
    }

    /**
     * Sets the value of the deskripsiPanjang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeskripsiPanjang(String value) {
        this.deskripsiPanjang = value;
    }

    /**
     * Gets the value of the nominalTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNominalTransaksi() {
        return nominalTransaksi;
    }

    /**
     * Sets the value of the nominalTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNominalTransaksi(String value) {
        this.nominalTransaksi = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "PaymentItem [kodeTransaksi=" + kodeTransaksi
				+ ", deskripsiPendek=" + deskripsiPendek
				+ ", deskripsiPanjang=" + deskripsiPanjang
				+ ", nominalTransaksi=" + nominalTransaksi + "]";
	}

}
