//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 06:31:15 PM ICT 
//


package h2humplg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomorPembayaran" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTagihan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fakultas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jurusan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="angkatan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jumlahItem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemPembayaran" type="{H2hUmplg}ArrayOfPaymentItem" minOccurs="0"/>
 *         &lt;element name="totalNominal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentResponse", propOrder = {
    "nomorPembayaran",
    "idTagihan",
    "nama",
    "fakultas",
    "jurusan",
    "strata",
    "angkatan",
    "jumlahItem",
    "itemPembayaran",
    "totalNominal",
    "code",
    "message",
    "origin"
})
public class PaymentResponse {

    protected String nomorPembayaran;
    protected String idTagihan;
    protected String nama;
    protected String fakultas;
    protected String jurusan;
    protected String strata;
    protected String angkatan;
    protected String jumlahItem;
    protected ArrayOfPaymentItem itemPembayaran;
    protected String totalNominal;
    protected String code;
    protected String message;
    protected String origin;

    /**
     * Gets the value of the nomorPembayaran property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomorPembayaran() {
        return nomorPembayaran;
    }

    /**
     * Sets the value of the nomorPembayaran property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomorPembayaran(String value) {
        this.nomorPembayaran = value;
    }

    /**
     * Gets the value of the idTagihan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTagihan() {
        return idTagihan;
    }

    /**
     * Sets the value of the idTagihan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTagihan(String value) {
        this.idTagihan = value;
    }

    /**
     * Gets the value of the nama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNama() {
        return nama;
    }

    /**
     * Sets the value of the nama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNama(String value) {
        this.nama = value;
    }

    /**
     * Gets the value of the fakultas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFakultas() {
        return fakultas;
    }

    /**
     * Sets the value of the fakultas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFakultas(String value) {
        this.fakultas = value;
    }

    /**
     * Gets the value of the jurusan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurusan() {
        return jurusan;
    }

    /**
     * Sets the value of the jurusan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurusan(String value) {
        this.jurusan = value;
    }

    /**
     * Gets the value of the strata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrata() {
        return strata;
    }

    /**
     * Sets the value of the strata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrata(String value) {
        this.strata = value;
    }

    /**
     * Gets the value of the angkatan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAngkatan() {
        return angkatan;
    }

    /**
     * Sets the value of the angkatan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAngkatan(String value) {
        this.angkatan = value;
    }

    /**
     * Gets the value of the jumlahItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJumlahItem() {
        return jumlahItem;
    }

    /**
     * Sets the value of the jumlahItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJumlahItem(String value) {
        this.jumlahItem = value;
    }

    /**
     * Gets the value of the itemPembayaran property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPaymentItem }
     *     
     */
    public ArrayOfPaymentItem getItemPembayaran() {
        return itemPembayaran;
    }

    /**
     * Sets the value of the itemPembayaran property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPaymentItem }
     *     
     */
    public void setItemPembayaran(ArrayOfPaymentItem value) {
        this.itemPembayaran = value;
    }

    /**
     * Gets the value of the totalNominal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalNominal() {
        return totalNominal;
    }

    /**
     * Sets the value of the totalNominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalNominal(String value) {
        this.totalNominal = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "PaymentResponse [nomorPembayaran=" + nomorPembayaran
				+ ", idTagihan=" + idTagihan + ", nama=" + nama + ", fakultas="
				+ fakultas + ", jurusan=" + jurusan + ", strata=" + strata
				+ ", angkatan=" + angkatan + ", jumlahItem=" + jumlahItem
				+ ", itemPembayaran=" + itemPembayaran + ", totalNominal="
				+ totalNominal + ", code=" + code + ", message=" + message
				+ ", origin=" + origin + "]";
	}

}
